name: merge-to-main

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  APOLLO_KEY: ${{ secrets.APOLLO_KEY }}
  APOLLO_VCS_COMMIT: ${{ github.event.pull_request.head.sha }}
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  deploy-monolith:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to fly
        run: flyctl deploy --remote-only

  publish-schemas:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: apollosolutions/rover-actions/install-rover-cli@v1

      - name: Publish checkout schema
        working-directory: ./subgraphs/checkout
        run: |
          rover subgraph publish apollo-retail-supergraph@prod \
            --name checkout \
            --schema schema.graphql

      - name: Publish discovery schema
        working-directory: ./subgraphs/discovery
        run: |
          rover subgraph publish apollo-retail-supergraph@prod \
            --name discovery \
            --schema schema.graphql

      - name: Publish inventory schema
        working-directory: ./subgraphs/inventory
        run: |
          rover subgraph publish apollo-retail-supergraph@prod \
            --name inventory \
            --schema schema.graphql

      - name: Publish orders schema
        working-directory: ./subgraphs/orders
        run: |
          rover subgraph publish apollo-retail-supergraph@prod \
            --name orders \
            --schema schema.graphql

      - name: Publish products schema
        working-directory: ./subgraphs/products
        run: |
          rover subgraph publish apollo-retail-supergraph@prod \
            --name products \
            --schema schema.graphql

      - name: Publish reviews schema
        working-directory: ./subgraphs/reviews
        run: |
          rover subgraph publish apollo-retail-supergraph@prod \
            --name reviews \
            --schema schema.graphql

      - name: Publish shipping schema
        working-directory: ./subgraphs/shipping
        run: |
          rover subgraph publish apollo-retail-supergraph@prod \
            --name shipping \
            --schema schema.graphql

      - name: Publish users schema
        working-directory: ./subgraphs/users
        run: |
          rover subgraph publish apollo-retail-supergraph@prod \
            --name users \
            --schema schema.graphql

  publish-README:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: apollosolutions/rover-actions/install-rover-cli@v1

      - name: Publish README
        run: rover readme publish apollo-retail-supergraph@prod --file README.md
