name: pr-check-code

on: pull_request

jobs:
  npm-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: "npm"

      - run: npm ci

  schema-checks:
    runs-on: ubuntu-latest
    needs: [checkout]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Rover
        run: |
          curl -sSL https://rover.apollo.dev/nix/latest | sh
          echo "$HOME/.rover/bin" >> $GITHUB_PATH

      - name: Check orders subgraph
        run: |
          rover subgraph check ${{ secrets.APOLLO_GRAPH_ID }}@test \
            --name orders \
            --schema ./services/orders/schema.graphql
